services:
  homebox:
    image: homebox
    build:
      context: .
      dockerfile: ./Dockerfile.hardened
      args:
        - COMMIT=head
        - BUILD_TIME=0001-01-01T00:00:00Z
      x-bake:
        platforms:
            - linux/amd64
            - linux/arm64
            - linux/arm/v7
    environment:
      - HBOX_DEBUG=true
      - HBOX_LOGGER_LEVEL=-1
      # OIDC configuration
      - HBOX_OIDC_ENABLED=true
      - HBOX_OIDC_ISSUER_URL=https://your-oidc.example.com/realms/homebox
      - HBOX_OIDC_CLIENT_ID=homebox-client
      - HBOX_OIDC_CLIENT_SECRET=REPLACE_ME
      - HBOX_OIDC_REDIRECT_URL=https://your-homebox.example.com/api/v1/auth/oidc/callback
      # Optional OIDC tuning
      - HBOX_OIDC_SCOPES=openid email profile groups
      - HBOX_OIDC_ROLES_CLAIM=groups
      - HBOX_OIDC_ADMIN_ROLE=admin
      - HBOX_OIDC_USER_ROLE=user
    ports:
      - 3100:7745
