services:
  homebox:
    image: homebox
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - COMMIT=head
        - BUILD_TIME=0001-01-01T00:00:00Z
      x-bake:
        platforms:
            - linux/amd64
            - linux/arm64
            - linux/arm
    environment:
      - HBOX_LOGGER_LEVEL=-1
      # - HBOX_WEB_APP_BASE=/homebox  # Serve under a sub-path (default: /, trailing slash auto-added)
    ports:
      - 3100:7745
