// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entityfield"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// EntityFieldDelete is the builder for deleting a EntityField entity.
type EntityFieldDelete struct {
	config
	hooks    []Hook
	mutation *EntityFieldMutation
}

// Where appends a list predicates to the EntityFieldDelete builder.
func (efd *EntityFieldDelete) Where(ps ...predicate.EntityField) *EntityFieldDelete {
	efd.mutation.Where(ps...)
	return efd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (efd *EntityFieldDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, efd.sqlExec, efd.mutation, efd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (efd *EntityFieldDelete) ExecX(ctx context.Context) int {
	n, err := efd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (efd *EntityFieldDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(entityfield.Table, sqlgraph.NewFieldSpec(entityfield.FieldID, field.TypeUUID))
	if ps := efd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, efd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	efd.mutation.done = true
	return affected, err
}

// EntityFieldDeleteOne is the builder for deleting a single EntityField entity.
type EntityFieldDeleteOne struct {
	efd *EntityFieldDelete
}

// Where appends a list predicates to the EntityFieldDelete builder.
func (efdo *EntityFieldDeleteOne) Where(ps ...predicate.EntityField) *EntityFieldDeleteOne {
	efdo.efd.mutation.Where(ps...)
	return efdo
}

// Exec executes the deletion query.
func (efdo *EntityFieldDeleteOne) Exec(ctx context.Context) error {
	n, err := efdo.efd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{entityfield.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (efdo *EntityFieldDeleteOne) ExecX(ctx context.Context) {
	if err := efdo.Exec(ctx); err != nil {
		panic(err)
	}
}
