// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/itemtemplate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/templatefield"
)

// ItemTemplateCreate is the builder for creating a ItemTemplate entity.
type ItemTemplateCreate struct {
	config
	mutation *ItemTemplateMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ItemTemplateCreate) SetCreatedAt(v time.Time) *ItemTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableCreatedAt(v *time.Time) *ItemTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ItemTemplateCreate) SetUpdatedAt(v time.Time) *ItemTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableUpdatedAt(v *time.Time) *ItemTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ItemTemplateCreate) SetName(v string) *ItemTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ItemTemplateCreate) SetDescription(v string) *ItemTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDescription(v *string) *ItemTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ItemTemplateCreate) SetNotes(v string) *ItemTemplateCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableNotes(v *string) *ItemTemplateCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetDefaultQuantity sets the "default_quantity" field.
func (_c *ItemTemplateCreate) SetDefaultQuantity(v int) *ItemTemplateCreate {
	_c.mutation.SetDefaultQuantity(v)
	return _c
}

// SetNillableDefaultQuantity sets the "default_quantity" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDefaultQuantity(v *int) *ItemTemplateCreate {
	if v != nil {
		_c.SetDefaultQuantity(*v)
	}
	return _c
}

// SetDefaultInsured sets the "default_insured" field.
func (_c *ItemTemplateCreate) SetDefaultInsured(v bool) *ItemTemplateCreate {
	_c.mutation.SetDefaultInsured(v)
	return _c
}

// SetNillableDefaultInsured sets the "default_insured" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDefaultInsured(v *bool) *ItemTemplateCreate {
	if v != nil {
		_c.SetDefaultInsured(*v)
	}
	return _c
}

// SetDefaultName sets the "default_name" field.
func (_c *ItemTemplateCreate) SetDefaultName(v string) *ItemTemplateCreate {
	_c.mutation.SetDefaultName(v)
	return _c
}

// SetNillableDefaultName sets the "default_name" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDefaultName(v *string) *ItemTemplateCreate {
	if v != nil {
		_c.SetDefaultName(*v)
	}
	return _c
}

// SetDefaultDescription sets the "default_description" field.
func (_c *ItemTemplateCreate) SetDefaultDescription(v string) *ItemTemplateCreate {
	_c.mutation.SetDefaultDescription(v)
	return _c
}

// SetNillableDefaultDescription sets the "default_description" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDefaultDescription(v *string) *ItemTemplateCreate {
	if v != nil {
		_c.SetDefaultDescription(*v)
	}
	return _c
}

// SetDefaultManufacturer sets the "default_manufacturer" field.
func (_c *ItemTemplateCreate) SetDefaultManufacturer(v string) *ItemTemplateCreate {
	_c.mutation.SetDefaultManufacturer(v)
	return _c
}

// SetNillableDefaultManufacturer sets the "default_manufacturer" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDefaultManufacturer(v *string) *ItemTemplateCreate {
	if v != nil {
		_c.SetDefaultManufacturer(*v)
	}
	return _c
}

// SetDefaultModelNumber sets the "default_model_number" field.
func (_c *ItemTemplateCreate) SetDefaultModelNumber(v string) *ItemTemplateCreate {
	_c.mutation.SetDefaultModelNumber(v)
	return _c
}

// SetNillableDefaultModelNumber sets the "default_model_number" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDefaultModelNumber(v *string) *ItemTemplateCreate {
	if v != nil {
		_c.SetDefaultModelNumber(*v)
	}
	return _c
}

// SetDefaultLifetimeWarranty sets the "default_lifetime_warranty" field.
func (_c *ItemTemplateCreate) SetDefaultLifetimeWarranty(v bool) *ItemTemplateCreate {
	_c.mutation.SetDefaultLifetimeWarranty(v)
	return _c
}

// SetNillableDefaultLifetimeWarranty sets the "default_lifetime_warranty" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDefaultLifetimeWarranty(v *bool) *ItemTemplateCreate {
	if v != nil {
		_c.SetDefaultLifetimeWarranty(*v)
	}
	return _c
}

// SetDefaultWarrantyDetails sets the "default_warranty_details" field.
func (_c *ItemTemplateCreate) SetDefaultWarrantyDetails(v string) *ItemTemplateCreate {
	_c.mutation.SetDefaultWarrantyDetails(v)
	return _c
}

// SetNillableDefaultWarrantyDetails sets the "default_warranty_details" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableDefaultWarrantyDetails(v *string) *ItemTemplateCreate {
	if v != nil {
		_c.SetDefaultWarrantyDetails(*v)
	}
	return _c
}

// SetIncludeWarrantyFields sets the "include_warranty_fields" field.
func (_c *ItemTemplateCreate) SetIncludeWarrantyFields(v bool) *ItemTemplateCreate {
	_c.mutation.SetIncludeWarrantyFields(v)
	return _c
}

// SetNillableIncludeWarrantyFields sets the "include_warranty_fields" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableIncludeWarrantyFields(v *bool) *ItemTemplateCreate {
	if v != nil {
		_c.SetIncludeWarrantyFields(*v)
	}
	return _c
}

// SetIncludePurchaseFields sets the "include_purchase_fields" field.
func (_c *ItemTemplateCreate) SetIncludePurchaseFields(v bool) *ItemTemplateCreate {
	_c.mutation.SetIncludePurchaseFields(v)
	return _c
}

// SetNillableIncludePurchaseFields sets the "include_purchase_fields" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableIncludePurchaseFields(v *bool) *ItemTemplateCreate {
	if v != nil {
		_c.SetIncludePurchaseFields(*v)
	}
	return _c
}

// SetIncludeSoldFields sets the "include_sold_fields" field.
func (_c *ItemTemplateCreate) SetIncludeSoldFields(v bool) *ItemTemplateCreate {
	_c.mutation.SetIncludeSoldFields(v)
	return _c
}

// SetNillableIncludeSoldFields sets the "include_sold_fields" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableIncludeSoldFields(v *bool) *ItemTemplateCreate {
	if v != nil {
		_c.SetIncludeSoldFields(*v)
	}
	return _c
}

// SetDefaultTagIds sets the "default_tag_ids" field.
func (_c *ItemTemplateCreate) SetDefaultTagIds(v []uuid.UUID) *ItemTemplateCreate {
	_c.mutation.SetDefaultTagIds(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ItemTemplateCreate) SetID(v uuid.UUID) *ItemTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableID(v *uuid.UUID) *ItemTemplateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_c *ItemTemplateCreate) SetGroupID(id uuid.UUID) *ItemTemplateCreate {
	_c.mutation.SetGroupID(id)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *ItemTemplateCreate) SetGroup(v *Group) *ItemTemplateCreate {
	return _c.SetGroupID(v.ID)
}

// AddFieldIDs adds the "fields" edge to the TemplateField entity by IDs.
func (_c *ItemTemplateCreate) AddFieldIDs(ids ...uuid.UUID) *ItemTemplateCreate {
	_c.mutation.AddFieldIDs(ids...)
	return _c
}

// AddFields adds the "fields" edges to the TemplateField entity.
func (_c *ItemTemplateCreate) AddFields(v ...*TemplateField) *ItemTemplateCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFieldIDs(ids...)
}

// SetLocationID sets the "location" edge to the Entity entity by ID.
func (_c *ItemTemplateCreate) SetLocationID(id uuid.UUID) *ItemTemplateCreate {
	_c.mutation.SetLocationID(id)
	return _c
}

// SetNillableLocationID sets the "location" edge to the Entity entity by ID if the given value is not nil.
func (_c *ItemTemplateCreate) SetNillableLocationID(id *uuid.UUID) *ItemTemplateCreate {
	if id != nil {
		_c = _c.SetLocationID(*id)
	}
	return _c
}

// SetLocation sets the "location" edge to the Entity entity.
func (_c *ItemTemplateCreate) SetLocation(v *Entity) *ItemTemplateCreate {
	return _c.SetLocationID(v.ID)
}

// Mutation returns the ItemTemplateMutation object of the builder.
func (_c *ItemTemplateCreate) Mutation() *ItemTemplateMutation {
	return _c.mutation
}

// Save creates the ItemTemplate in the database.
func (_c *ItemTemplateCreate) Save(ctx context.Context) (*ItemTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemTemplateCreate) SaveX(ctx context.Context) *ItemTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemTemplateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := itemtemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := itemtemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DefaultQuantity(); !ok {
		v := itemtemplate.DefaultDefaultQuantity
		_c.mutation.SetDefaultQuantity(v)
	}
	if _, ok := _c.mutation.DefaultInsured(); !ok {
		v := itemtemplate.DefaultDefaultInsured
		_c.mutation.SetDefaultInsured(v)
	}
	if _, ok := _c.mutation.DefaultLifetimeWarranty(); !ok {
		v := itemtemplate.DefaultDefaultLifetimeWarranty
		_c.mutation.SetDefaultLifetimeWarranty(v)
	}
	if _, ok := _c.mutation.IncludeWarrantyFields(); !ok {
		v := itemtemplate.DefaultIncludeWarrantyFields
		_c.mutation.SetIncludeWarrantyFields(v)
	}
	if _, ok := _c.mutation.IncludePurchaseFields(); !ok {
		v := itemtemplate.DefaultIncludePurchaseFields
		_c.mutation.SetIncludePurchaseFields(v)
	}
	if _, ok := _c.mutation.IncludeSoldFields(); !ok {
		v := itemtemplate.DefaultIncludeSoldFields
		_c.mutation.SetIncludeSoldFields(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := itemtemplate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemTemplateCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ItemTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ItemTemplate.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ItemTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := itemtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ItemTemplate.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := itemtemplate.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ItemTemplate.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Notes(); ok {
		if err := itemtemplate.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "ItemTemplate.notes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultQuantity(); !ok {
		return &ValidationError{Name: "default_quantity", err: errors.New(`ent: missing required field "ItemTemplate.default_quantity"`)}
	}
	if _, ok := _c.mutation.DefaultInsured(); !ok {
		return &ValidationError{Name: "default_insured", err: errors.New(`ent: missing required field "ItemTemplate.default_insured"`)}
	}
	if v, ok := _c.mutation.DefaultName(); ok {
		if err := itemtemplate.DefaultNameValidator(v); err != nil {
			return &ValidationError{Name: "default_name", err: fmt.Errorf(`ent: validator failed for field "ItemTemplate.default_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DefaultDescription(); ok {
		if err := itemtemplate.DefaultDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "default_description", err: fmt.Errorf(`ent: validator failed for field "ItemTemplate.default_description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DefaultManufacturer(); ok {
		if err := itemtemplate.DefaultManufacturerValidator(v); err != nil {
			return &ValidationError{Name: "default_manufacturer", err: fmt.Errorf(`ent: validator failed for field "ItemTemplate.default_manufacturer": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DefaultModelNumber(); ok {
		if err := itemtemplate.DefaultModelNumberValidator(v); err != nil {
			return &ValidationError{Name: "default_model_number", err: fmt.Errorf(`ent: validator failed for field "ItemTemplate.default_model_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultLifetimeWarranty(); !ok {
		return &ValidationError{Name: "default_lifetime_warranty", err: errors.New(`ent: missing required field "ItemTemplate.default_lifetime_warranty"`)}
	}
	if v, ok := _c.mutation.DefaultWarrantyDetails(); ok {
		if err := itemtemplate.DefaultWarrantyDetailsValidator(v); err != nil {
			return &ValidationError{Name: "default_warranty_details", err: fmt.Errorf(`ent: validator failed for field "ItemTemplate.default_warranty_details": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IncludeWarrantyFields(); !ok {
		return &ValidationError{Name: "include_warranty_fields", err: errors.New(`ent: missing required field "ItemTemplate.include_warranty_fields"`)}
	}
	if _, ok := _c.mutation.IncludePurchaseFields(); !ok {
		return &ValidationError{Name: "include_purchase_fields", err: errors.New(`ent: missing required field "ItemTemplate.include_purchase_fields"`)}
	}
	if _, ok := _c.mutation.IncludeSoldFields(); !ok {
		return &ValidationError{Name: "include_sold_fields", err: errors.New(`ent: missing required field "ItemTemplate.include_sold_fields"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "ItemTemplate.group"`)}
	}
	return nil
}

func (_c *ItemTemplateCreate) sqlSave(ctx context.Context) (*ItemTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemTemplateCreate) createSpec() (*ItemTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(itemtemplate.Table, sqlgraph.NewFieldSpec(itemtemplate.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(itemtemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(itemtemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(itemtemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(itemtemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(itemtemplate.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.DefaultQuantity(); ok {
		_spec.SetField(itemtemplate.FieldDefaultQuantity, field.TypeInt, value)
		_node.DefaultQuantity = value
	}
	if value, ok := _c.mutation.DefaultInsured(); ok {
		_spec.SetField(itemtemplate.FieldDefaultInsured, field.TypeBool, value)
		_node.DefaultInsured = value
	}
	if value, ok := _c.mutation.DefaultName(); ok {
		_spec.SetField(itemtemplate.FieldDefaultName, field.TypeString, value)
		_node.DefaultName = value
	}
	if value, ok := _c.mutation.DefaultDescription(); ok {
		_spec.SetField(itemtemplate.FieldDefaultDescription, field.TypeString, value)
		_node.DefaultDescription = value
	}
	if value, ok := _c.mutation.DefaultManufacturer(); ok {
		_spec.SetField(itemtemplate.FieldDefaultManufacturer, field.TypeString, value)
		_node.DefaultManufacturer = value
	}
	if value, ok := _c.mutation.DefaultModelNumber(); ok {
		_spec.SetField(itemtemplate.FieldDefaultModelNumber, field.TypeString, value)
		_node.DefaultModelNumber = value
	}
	if value, ok := _c.mutation.DefaultLifetimeWarranty(); ok {
		_spec.SetField(itemtemplate.FieldDefaultLifetimeWarranty, field.TypeBool, value)
		_node.DefaultLifetimeWarranty = value
	}
	if value, ok := _c.mutation.DefaultWarrantyDetails(); ok {
		_spec.SetField(itemtemplate.FieldDefaultWarrantyDetails, field.TypeString, value)
		_node.DefaultWarrantyDetails = value
	}
	if value, ok := _c.mutation.IncludeWarrantyFields(); ok {
		_spec.SetField(itemtemplate.FieldIncludeWarrantyFields, field.TypeBool, value)
		_node.IncludeWarrantyFields = value
	}
	if value, ok := _c.mutation.IncludePurchaseFields(); ok {
		_spec.SetField(itemtemplate.FieldIncludePurchaseFields, field.TypeBool, value)
		_node.IncludePurchaseFields = value
	}
	if value, ok := _c.mutation.IncludeSoldFields(); ok {
		_spec.SetField(itemtemplate.FieldIncludeSoldFields, field.TypeBool, value)
		_node.IncludeSoldFields = value
	}
	if value, ok := _c.mutation.DefaultTagIds(); ok {
		_spec.SetField(itemtemplate.FieldDefaultTagIds, field.TypeJSON, value)
		_node.DefaultTagIds = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemtemplate.GroupTable,
			Columns: []string{itemtemplate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_item_templates = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FieldsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itemtemplate.FieldsTable,
			Columns: []string{itemtemplate.FieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefield.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   itemtemplate.LocationTable,
			Columns: []string{itemtemplate.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.item_template_location = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ItemTemplateCreateBulk is the builder for creating many ItemTemplate entities in bulk.
type ItemTemplateCreateBulk struct {
	config
	err      error
	builders []*ItemTemplateCreate
}

// Save creates the ItemTemplate entities in the database.
func (_c *ItemTemplateCreateBulk) Save(ctx context.Context) ([]*ItemTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ItemTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemTemplateCreateBulk) SaveX(ctx context.Context) []*ItemTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
