// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/labeltemplate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// LabelTemplate is the model entity for the LabelTemplate schema.
type LabelTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Label width in mm
	Width float64 `json:"width,omitempty"`
	// Label height in mm
	Height float64 `json:"height,omitempty"`
	// Preset size key like 'brother_dk2205'
	Preset string `json:"preset,omitempty"`
	// Whether template is shared with group
	IsShared bool `json:"is_shared,omitempty"`
	// Fabric.js compatible canvas JSON
	CanvasData map[string]interface{} `json:"canvas_data,omitempty"`
	// Output format: png, pdf
	OutputFormat string `json:"output_format,omitempty"`
	// Output DPI for rendering
	Dpi int `json:"dpi,omitempty"`
	// Brother media type like 'DK-22251' for direct printing
	MediaType string `json:"media_type,omitempty"`
	// User who created this template
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LabelTemplateQuery when eager-loading is set.
	Edges                 LabelTemplateEdges `json:"edges"`
	group_label_templates *uuid.UUID
	selectValues          sql.SelectValues
}

// LabelTemplateEdges holds the relations/edges for other nodes in the graph.
type LabelTemplateEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LabelTemplateEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LabelTemplateEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LabelTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case labeltemplate.FieldCanvasData:
			values[i] = new([]byte)
		case labeltemplate.FieldIsShared:
			values[i] = new(sql.NullBool)
		case labeltemplate.FieldWidth, labeltemplate.FieldHeight:
			values[i] = new(sql.NullFloat64)
		case labeltemplate.FieldDpi:
			values[i] = new(sql.NullInt64)
		case labeltemplate.FieldName, labeltemplate.FieldDescription, labeltemplate.FieldPreset, labeltemplate.FieldOutputFormat, labeltemplate.FieldMediaType:
			values[i] = new(sql.NullString)
		case labeltemplate.FieldCreatedAt, labeltemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case labeltemplate.FieldID, labeltemplate.FieldOwnerID:
			values[i] = new(uuid.UUID)
		case labeltemplate.ForeignKeys[0]: // group_label_templates
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LabelTemplate fields.
func (_m *LabelTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case labeltemplate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case labeltemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case labeltemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case labeltemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case labeltemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case labeltemplate.FieldWidth:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = value.Float64
			}
		case labeltemplate.FieldHeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = value.Float64
			}
		case labeltemplate.FieldPreset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preset", values[i])
			} else if value.Valid {
				_m.Preset = value.String
			}
		case labeltemplate.FieldIsShared:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_shared", values[i])
			} else if value.Valid {
				_m.IsShared = value.Bool
			}
		case labeltemplate.FieldCanvasData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field canvas_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CanvasData); err != nil {
					return fmt.Errorf("unmarshal field canvas_data: %w", err)
				}
			}
		case labeltemplate.FieldOutputFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output_format", values[i])
			} else if value.Valid {
				_m.OutputFormat = value.String
			}
		case labeltemplate.FieldDpi:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dpi", values[i])
			} else if value.Valid {
				_m.Dpi = int(value.Int64)
			}
		case labeltemplate.FieldMediaType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_type", values[i])
			} else if value.Valid {
				_m.MediaType = value.String
			}
		case labeltemplate.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				_m.OwnerID = *value
			}
		case labeltemplate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field group_label_templates", values[i])
			} else if value.Valid {
				_m.group_label_templates = new(uuid.UUID)
				*_m.group_label_templates = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LabelTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *LabelTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the LabelTemplate entity.
func (_m *LabelTemplate) QueryGroup() *GroupQuery {
	return NewLabelTemplateClient(_m.config).QueryGroup(_m)
}

// QueryOwner queries the "owner" edge of the LabelTemplate entity.
func (_m *LabelTemplate) QueryOwner() *UserQuery {
	return NewLabelTemplateClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this LabelTemplate.
// Note that you need to call LabelTemplate.Unwrap() before calling this method if this LabelTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LabelTemplate) Update() *LabelTemplateUpdateOne {
	return NewLabelTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LabelTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LabelTemplate) Unwrap() *LabelTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LabelTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LabelTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("LabelTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("preset=")
	builder.WriteString(_m.Preset)
	builder.WriteString(", ")
	builder.WriteString("is_shared=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsShared))
	builder.WriteString(", ")
	builder.WriteString("canvas_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanvasData))
	builder.WriteString(", ")
	builder.WriteString("output_format=")
	builder.WriteString(_m.OutputFormat)
	builder.WriteString(", ")
	builder.WriteString("dpi=")
	builder.WriteString(fmt.Sprintf("%v", _m.Dpi))
	builder.WriteString(", ")
	builder.WriteString("media_type=")
	builder.WriteString(_m.MediaType)
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteByte(')')
	return builder.String()
}

// LabelTemplates is a parsable slice of LabelTemplate.
type LabelTemplates []*LabelTemplate
