// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/permissiongroup"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// PermissionGroupCreate is the builder for creating a PermissionGroup entity.
type PermissionGroupCreate struct {
	config
	mutation *PermissionGroupMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PermissionGroupCreate) SetCreatedAt(v time.Time) *PermissionGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableCreatedAt(v *time.Time) *PermissionGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PermissionGroupCreate) SetUpdatedAt(v time.Time) *PermissionGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableUpdatedAt(v *time.Time) *PermissionGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PermissionGroupCreate) SetName(v string) *PermissionGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PermissionGroupCreate) SetDescription(v string) *PermissionGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableDescription(v *string) *PermissionGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PermissionGroupCreate) SetGroupID(v uuid.UUID) *PermissionGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPermissions sets the "permissions" field.
func (_c *PermissionGroupCreate) SetPermissions(v []string) *PermissionGroupCreate {
	_c.mutation.SetPermissions(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PermissionGroupCreate) SetID(v uuid.UUID) *PermissionGroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PermissionGroupCreate) SetNillableID(v *uuid.UUID) *PermissionGroupCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *PermissionGroupCreate) SetGroup(v *Group) *PermissionGroupCreate {
	return _c.SetGroupID(v.ID)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *PermissionGroupCreate) AddUserIDs(ids ...uuid.UUID) *PermissionGroupCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *PermissionGroupCreate) AddUsers(v ...*User) *PermissionGroupCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// Mutation returns the PermissionGroupMutation object of the builder.
func (_c *PermissionGroupCreate) Mutation() *PermissionGroupMutation {
	return _c.mutation
}

// Save creates the PermissionGroup in the database.
func (_c *PermissionGroupCreate) Save(ctx context.Context) (*PermissionGroup, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionGroupCreate) SaveX(ctx context.Context) *PermissionGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PermissionGroupCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if permissiongroup.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized permissiongroup.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := permissiongroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if permissiongroup.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized permissiongroup.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := permissiongroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		v := permissiongroup.DefaultPermissions
		_c.mutation.SetPermissions(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if permissiongroup.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized permissiongroup.DefaultID (forgotten import ent/runtime?)")
		}
		v := permissiongroup.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PermissionGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PermissionGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PermissionGroup.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := permissiongroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PermissionGroup.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := permissiongroup.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "PermissionGroup.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "PermissionGroup.group_id"`)}
	}
	if _, ok := _c.mutation.Permissions(); !ok {
		return &ValidationError{Name: "permissions", err: errors.New(`ent: missing required field "PermissionGroup.permissions"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "PermissionGroup.group"`)}
	}
	return nil
}

func (_c *PermissionGroupCreate) sqlSave(ctx context.Context) (*PermissionGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionGroupCreate) createSpec() (*PermissionGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &PermissionGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permissiongroup.Table, sqlgraph.NewFieldSpec(permissiongroup.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(permissiongroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(permissiongroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(permissiongroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(permissiongroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Permissions(); ok {
		_spec.SetField(permissiongroup.FieldPermissions, field.TypeJSON, value)
		_node.Permissions = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permissiongroup.GroupTable,
			Columns: []string{permissiongroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   permissiongroup.UsersTable,
			Columns: permissiongroup.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PermissionGroupCreateBulk is the builder for creating many PermissionGroup entities in bulk.
type PermissionGroupCreateBulk struct {
	config
	err      error
	builders []*PermissionGroupCreate
}

// Save creates the PermissionGroup entities in the database.
func (_c *PermissionGroupCreateBulk) Save(ctx context.Context) ([]*PermissionGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PermissionGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionGroupCreateBulk) SaveX(ctx context.Context) []*PermissionGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
