package backupsetup

import (
	"bufio"
	"bytes"
	"fmt"
	"strings"
)

// KV is one environment variable.
type KV struct{ Key, Value string }

// Plan is what a run would write, and what it decided about the key.
type Plan struct {
	Vars []KV
	// KeyKept is true when an existing encryption key was reused, KeyRotated
	// when it was deliberately replaced, and KeyGenerated when there was none.
	KeyKept, KeyRotated, KeyGenerated bool
}

// IsSecret reports whether a variable's value must never be printed.
func IsSecret(key string) bool {
	return strings.HasSuffix(key, "_SECRET") || key == EnvEncryptionKey
}

// ParseEnv reads KEY=VALUE lines, ignoring comments and blanks. Values may be
// wrapped in matching single or double quotes.
func ParseEnv(b []byte) map[string]string {
	out := map[string]string{}
	sc := bufio.NewScanner(bytes.NewReader(b))
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		k, v = strings.TrimSpace(k), strings.TrimSpace(v)
		if len(v) >= 2 && (v[0] == '"' || v[0] == '\'') && v[len(v)-1] == v[0] {
			v = v[1 : len(v)-1]
		}
		out[k] = v
	}
	return out
}

// Build turns validated params into the variables to write. existing holds the
// values already in the target file: the encryption key is kept unless a
// rotation was asked for, because changing it makes every stored login
// unreadable.
func Build(p Params, existing map[string]string) Plan {
	var plan Plan
	add := func(k, v string) {
		if v != "" {
			plan.Vars = append(plan.Vars, KV{k, v})
		}
	}

	key := p.EncryptionKey
	switch {
	case key != "":
		if old := existing[EnvEncryptionKey]; old != "" && old != key {
			plan.KeyRotated = true
		}
	case existing[EnvEncryptionKey] != "" && !p.RotateKey:
		key = existing[EnvEncryptionKey]
		plan.KeyKept = true
	default:
		key = GenerateKey()
		plan.KeyGenerated = true
		plan.KeyRotated = existing[EnvEncryptionKey] != ""
	}
	add(EnvEncryptionKey, key)
	add(EnvLocalRoot, p.LocalRoot)
	if p.AllowCustomEndpoints {
		add(EnvCustomEndpoints, "true") // the server default is off
	}

	add(EnvGoogleID, p.Google.ClientID)
	add(EnvGoogleSecret, p.Google.ClientSecret)
	add(EnvMicrosoftID, p.Microsoft.ClientID)
	add(EnvMicrosoftSecret, p.Microsoft.ClientSecret)
	if p.Microsoft.Set() && p.MicrosoftTenant != "" && p.MicrosoftTenant != DefaultMicrosoftTen {
		add(EnvMicrosoftTenant, p.MicrosoftTenant)
	}
	add(EnvDropboxID, p.Dropbox.ClientID)
	add(EnvDropboxSecret, p.Dropbox.ClientSecret)

	if len(p.Providers()) > 0 && p.BaseURL != "" {
		scheme, host, err := ParseBaseURL(p.BaseURL)
		if err == nil {
			// The OIDC code prepends the scheme to this value, so it must be a bare
			// host. The scheme comes from the request, which behind a TLS proxy
			// means trusting X-Forwarded-Proto.
			add(EnvHostname, host)
			if scheme == "https" && p.BehindProxy {
				add(EnvTrustProxy, "true")
			}
		}
	}
	return plan
}

const sectionHeader = "# --- Homebox scheduled backups (generated by `homebox backup-config`) ---"

// Merge applies updates to an existing .env file's contents. Lines for the
// updated keys are replaced in place; new keys are appended under a header;
// everything else, including comments and unrelated variables, is untouched.
func Merge(existing []byte, updates []KV) []byte {
	want := map[string]string{}
	for _, kv := range updates {
		want[kv.Key] = kv.Value
	}

	var out []string
	done := map[string]bool{}
	if len(existing) > 0 {
		sc := bufio.NewScanner(bytes.NewReader(existing))
		sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
		for sc.Scan() {
			line := sc.Text()
			trim := strings.TrimPrefix(strings.TrimSpace(line), "export ")
			if k, _, ok := strings.Cut(trim, "="); ok {
				k = strings.TrimSpace(k)
				if v, isManaged := want[k]; isManaged && !strings.HasPrefix(strings.TrimSpace(line), "#") {
					if !done[k] {
						out = append(out, k+"="+v)
						done[k] = true
					}
					continue // drop duplicate definitions of a managed key
				}
			}
			out = append(out, line)
		}
	}

	var missing []KV
	for _, kv := range updates {
		if !done[kv.Key] {
			missing = append(missing, kv)
		}
	}
	if len(missing) > 0 {
		if len(out) > 0 && strings.TrimSpace(out[len(out)-1]) != "" {
			out = append(out, "")
		}
		hasHeader := false
		for _, l := range out {
			if l == sectionHeader {
				hasHeader = true
			}
		}
		if !hasHeader {
			out = append(out, sectionHeader)
		}
		for _, kv := range missing {
			out = append(out, kv.Key+"="+kv.Value)
		}
	}
	return []byte(strings.Join(out, "\n") + "\n")
}

// Mask hides a secret for display, keeping a short prefix so the user can tell
// values apart.
func Mask(key, value string) string {
	if !IsSecret(key) {
		return value
	}
	if len(value) <= 6 {
		return "****"
	}
	return value[:3] + "****"
}

// Diff describes what changed between the existing file and the plan, with
// secrets masked, so a user can review it before anything is written.
func Diff(existing map[string]string, plan Plan) []string {
	var lines []string
	for _, kv := range plan.Vars {
		old, had := existing[kv.Key]
		switch {
		case !had:
			lines = append(lines, fmt.Sprintf("+ %s=%s", kv.Key, Mask(kv.Key, kv.Value)))
		case old != kv.Value:
			lines = append(lines, fmt.Sprintf("~ %s=%s (was %s)", kv.Key, Mask(kv.Key, kv.Value), Mask(kv.Key, old)))
		default:
			lines = append(lines, fmt.Sprintf("= %s (unchanged)", kv.Key))
		}
	}
	return lines
}
