// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// AuthRoles is the predicate function for authroles builders.
type AuthRoles func(*sql.Selector)

// AuthTokens is the predicate function for authtokens builders.
type AuthTokens func(*sql.Selector)

// Entity is the predicate function for entity builders.
type Entity func(*sql.Selector)

// EntityField is the predicate function for entityfield builders.
type EntityField func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupInvitationToken is the predicate function for groupinvitationtoken builders.
type GroupInvitationToken func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// MaintenanceEntry is the predicate function for maintenanceentry builders.
type MaintenanceEntry func(*sql.Selector)

// Notifier is the predicate function for notifier builders.
type Notifier func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
