// Code generated by ent, DO NOT EDIT.

package itemtemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDescription, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldNotes, v))
}

// DefaultQuantity applies equality check predicate on the "default_quantity" field. It's identical to DefaultQuantityEQ.
func DefaultQuantity(v int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultQuantity, v))
}

// DefaultInsured applies equality check predicate on the "default_insured" field. It's identical to DefaultInsuredEQ.
func DefaultInsured(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultInsured, v))
}

// DefaultName applies equality check predicate on the "default_name" field. It's identical to DefaultNameEQ.
func DefaultName(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultName, v))
}

// DefaultDescription applies equality check predicate on the "default_description" field. It's identical to DefaultDescriptionEQ.
func DefaultDescription(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultDescription, v))
}

// DefaultManufacturer applies equality check predicate on the "default_manufacturer" field. It's identical to DefaultManufacturerEQ.
func DefaultManufacturer(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultManufacturer, v))
}

// DefaultModelNumber applies equality check predicate on the "default_model_number" field. It's identical to DefaultModelNumberEQ.
func DefaultModelNumber(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultModelNumber, v))
}

// DefaultLifetimeWarranty applies equality check predicate on the "default_lifetime_warranty" field. It's identical to DefaultLifetimeWarrantyEQ.
func DefaultLifetimeWarranty(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultLifetimeWarranty, v))
}

// DefaultWarrantyDetails applies equality check predicate on the "default_warranty_details" field. It's identical to DefaultWarrantyDetailsEQ.
func DefaultWarrantyDetails(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultWarrantyDetails, v))
}

// IncludeWarrantyFields applies equality check predicate on the "include_warranty_fields" field. It's identical to IncludeWarrantyFieldsEQ.
func IncludeWarrantyFields(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldIncludeWarrantyFields, v))
}

// IncludePurchaseFields applies equality check predicate on the "include_purchase_fields" field. It's identical to IncludePurchaseFieldsEQ.
func IncludePurchaseFields(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldIncludePurchaseFields, v))
}

// IncludeSoldFields applies equality check predicate on the "include_sold_fields" field. It's identical to IncludeSoldFieldsEQ.
func IncludeSoldFields(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldIncludeSoldFields, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContainsFold(FieldDescription, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContainsFold(FieldNotes, v))
}

// DefaultQuantityEQ applies the EQ predicate on the "default_quantity" field.
func DefaultQuantityEQ(v int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultQuantity, v))
}

// DefaultQuantityNEQ applies the NEQ predicate on the "default_quantity" field.
func DefaultQuantityNEQ(v int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDefaultQuantity, v))
}

// DefaultQuantityIn applies the In predicate on the "default_quantity" field.
func DefaultQuantityIn(vs ...int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldDefaultQuantity, vs...))
}

// DefaultQuantityNotIn applies the NotIn predicate on the "default_quantity" field.
func DefaultQuantityNotIn(vs ...int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldDefaultQuantity, vs...))
}

// DefaultQuantityGT applies the GT predicate on the "default_quantity" field.
func DefaultQuantityGT(v int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldDefaultQuantity, v))
}

// DefaultQuantityGTE applies the GTE predicate on the "default_quantity" field.
func DefaultQuantityGTE(v int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldDefaultQuantity, v))
}

// DefaultQuantityLT applies the LT predicate on the "default_quantity" field.
func DefaultQuantityLT(v int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldDefaultQuantity, v))
}

// DefaultQuantityLTE applies the LTE predicate on the "default_quantity" field.
func DefaultQuantityLTE(v int) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldDefaultQuantity, v))
}

// DefaultInsuredEQ applies the EQ predicate on the "default_insured" field.
func DefaultInsuredEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultInsured, v))
}

// DefaultInsuredNEQ applies the NEQ predicate on the "default_insured" field.
func DefaultInsuredNEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDefaultInsured, v))
}

// DefaultNameEQ applies the EQ predicate on the "default_name" field.
func DefaultNameEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultName, v))
}

// DefaultNameNEQ applies the NEQ predicate on the "default_name" field.
func DefaultNameNEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDefaultName, v))
}

// DefaultNameIn applies the In predicate on the "default_name" field.
func DefaultNameIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldDefaultName, vs...))
}

// DefaultNameNotIn applies the NotIn predicate on the "default_name" field.
func DefaultNameNotIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldDefaultName, vs...))
}

// DefaultNameGT applies the GT predicate on the "default_name" field.
func DefaultNameGT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldDefaultName, v))
}

// DefaultNameGTE applies the GTE predicate on the "default_name" field.
func DefaultNameGTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldDefaultName, v))
}

// DefaultNameLT applies the LT predicate on the "default_name" field.
func DefaultNameLT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldDefaultName, v))
}

// DefaultNameLTE applies the LTE predicate on the "default_name" field.
func DefaultNameLTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldDefaultName, v))
}

// DefaultNameContains applies the Contains predicate on the "default_name" field.
func DefaultNameContains(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContains(FieldDefaultName, v))
}

// DefaultNameHasPrefix applies the HasPrefix predicate on the "default_name" field.
func DefaultNameHasPrefix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasPrefix(FieldDefaultName, v))
}

// DefaultNameHasSuffix applies the HasSuffix predicate on the "default_name" field.
func DefaultNameHasSuffix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasSuffix(FieldDefaultName, v))
}

// DefaultNameIsNil applies the IsNil predicate on the "default_name" field.
func DefaultNameIsNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIsNull(FieldDefaultName))
}

// DefaultNameNotNil applies the NotNil predicate on the "default_name" field.
func DefaultNameNotNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotNull(FieldDefaultName))
}

// DefaultNameEqualFold applies the EqualFold predicate on the "default_name" field.
func DefaultNameEqualFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEqualFold(FieldDefaultName, v))
}

// DefaultNameContainsFold applies the ContainsFold predicate on the "default_name" field.
func DefaultNameContainsFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContainsFold(FieldDefaultName, v))
}

// DefaultDescriptionEQ applies the EQ predicate on the "default_description" field.
func DefaultDescriptionEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultDescription, v))
}

// DefaultDescriptionNEQ applies the NEQ predicate on the "default_description" field.
func DefaultDescriptionNEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDefaultDescription, v))
}

// DefaultDescriptionIn applies the In predicate on the "default_description" field.
func DefaultDescriptionIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldDefaultDescription, vs...))
}

// DefaultDescriptionNotIn applies the NotIn predicate on the "default_description" field.
func DefaultDescriptionNotIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldDefaultDescription, vs...))
}

// DefaultDescriptionGT applies the GT predicate on the "default_description" field.
func DefaultDescriptionGT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldDefaultDescription, v))
}

// DefaultDescriptionGTE applies the GTE predicate on the "default_description" field.
func DefaultDescriptionGTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldDefaultDescription, v))
}

// DefaultDescriptionLT applies the LT predicate on the "default_description" field.
func DefaultDescriptionLT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldDefaultDescription, v))
}

// DefaultDescriptionLTE applies the LTE predicate on the "default_description" field.
func DefaultDescriptionLTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldDefaultDescription, v))
}

// DefaultDescriptionContains applies the Contains predicate on the "default_description" field.
func DefaultDescriptionContains(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContains(FieldDefaultDescription, v))
}

// DefaultDescriptionHasPrefix applies the HasPrefix predicate on the "default_description" field.
func DefaultDescriptionHasPrefix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasPrefix(FieldDefaultDescription, v))
}

// DefaultDescriptionHasSuffix applies the HasSuffix predicate on the "default_description" field.
func DefaultDescriptionHasSuffix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasSuffix(FieldDefaultDescription, v))
}

// DefaultDescriptionIsNil applies the IsNil predicate on the "default_description" field.
func DefaultDescriptionIsNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIsNull(FieldDefaultDescription))
}

// DefaultDescriptionNotNil applies the NotNil predicate on the "default_description" field.
func DefaultDescriptionNotNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotNull(FieldDefaultDescription))
}

// DefaultDescriptionEqualFold applies the EqualFold predicate on the "default_description" field.
func DefaultDescriptionEqualFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEqualFold(FieldDefaultDescription, v))
}

// DefaultDescriptionContainsFold applies the ContainsFold predicate on the "default_description" field.
func DefaultDescriptionContainsFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContainsFold(FieldDefaultDescription, v))
}

// DefaultManufacturerEQ applies the EQ predicate on the "default_manufacturer" field.
func DefaultManufacturerEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultManufacturer, v))
}

// DefaultManufacturerNEQ applies the NEQ predicate on the "default_manufacturer" field.
func DefaultManufacturerNEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDefaultManufacturer, v))
}

// DefaultManufacturerIn applies the In predicate on the "default_manufacturer" field.
func DefaultManufacturerIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldDefaultManufacturer, vs...))
}

// DefaultManufacturerNotIn applies the NotIn predicate on the "default_manufacturer" field.
func DefaultManufacturerNotIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldDefaultManufacturer, vs...))
}

// DefaultManufacturerGT applies the GT predicate on the "default_manufacturer" field.
func DefaultManufacturerGT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldDefaultManufacturer, v))
}

// DefaultManufacturerGTE applies the GTE predicate on the "default_manufacturer" field.
func DefaultManufacturerGTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldDefaultManufacturer, v))
}

// DefaultManufacturerLT applies the LT predicate on the "default_manufacturer" field.
func DefaultManufacturerLT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldDefaultManufacturer, v))
}

// DefaultManufacturerLTE applies the LTE predicate on the "default_manufacturer" field.
func DefaultManufacturerLTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldDefaultManufacturer, v))
}

// DefaultManufacturerContains applies the Contains predicate on the "default_manufacturer" field.
func DefaultManufacturerContains(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContains(FieldDefaultManufacturer, v))
}

// DefaultManufacturerHasPrefix applies the HasPrefix predicate on the "default_manufacturer" field.
func DefaultManufacturerHasPrefix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasPrefix(FieldDefaultManufacturer, v))
}

// DefaultManufacturerHasSuffix applies the HasSuffix predicate on the "default_manufacturer" field.
func DefaultManufacturerHasSuffix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasSuffix(FieldDefaultManufacturer, v))
}

// DefaultManufacturerIsNil applies the IsNil predicate on the "default_manufacturer" field.
func DefaultManufacturerIsNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIsNull(FieldDefaultManufacturer))
}

// DefaultManufacturerNotNil applies the NotNil predicate on the "default_manufacturer" field.
func DefaultManufacturerNotNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotNull(FieldDefaultManufacturer))
}

// DefaultManufacturerEqualFold applies the EqualFold predicate on the "default_manufacturer" field.
func DefaultManufacturerEqualFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEqualFold(FieldDefaultManufacturer, v))
}

// DefaultManufacturerContainsFold applies the ContainsFold predicate on the "default_manufacturer" field.
func DefaultManufacturerContainsFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContainsFold(FieldDefaultManufacturer, v))
}

// DefaultModelNumberEQ applies the EQ predicate on the "default_model_number" field.
func DefaultModelNumberEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultModelNumber, v))
}

// DefaultModelNumberNEQ applies the NEQ predicate on the "default_model_number" field.
func DefaultModelNumberNEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDefaultModelNumber, v))
}

// DefaultModelNumberIn applies the In predicate on the "default_model_number" field.
func DefaultModelNumberIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldDefaultModelNumber, vs...))
}

// DefaultModelNumberNotIn applies the NotIn predicate on the "default_model_number" field.
func DefaultModelNumberNotIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldDefaultModelNumber, vs...))
}

// DefaultModelNumberGT applies the GT predicate on the "default_model_number" field.
func DefaultModelNumberGT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldDefaultModelNumber, v))
}

// DefaultModelNumberGTE applies the GTE predicate on the "default_model_number" field.
func DefaultModelNumberGTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldDefaultModelNumber, v))
}

// DefaultModelNumberLT applies the LT predicate on the "default_model_number" field.
func DefaultModelNumberLT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldDefaultModelNumber, v))
}

// DefaultModelNumberLTE applies the LTE predicate on the "default_model_number" field.
func DefaultModelNumberLTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldDefaultModelNumber, v))
}

// DefaultModelNumberContains applies the Contains predicate on the "default_model_number" field.
func DefaultModelNumberContains(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContains(FieldDefaultModelNumber, v))
}

// DefaultModelNumberHasPrefix applies the HasPrefix predicate on the "default_model_number" field.
func DefaultModelNumberHasPrefix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasPrefix(FieldDefaultModelNumber, v))
}

// DefaultModelNumberHasSuffix applies the HasSuffix predicate on the "default_model_number" field.
func DefaultModelNumberHasSuffix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasSuffix(FieldDefaultModelNumber, v))
}

// DefaultModelNumberIsNil applies the IsNil predicate on the "default_model_number" field.
func DefaultModelNumberIsNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIsNull(FieldDefaultModelNumber))
}

// DefaultModelNumberNotNil applies the NotNil predicate on the "default_model_number" field.
func DefaultModelNumberNotNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotNull(FieldDefaultModelNumber))
}

// DefaultModelNumberEqualFold applies the EqualFold predicate on the "default_model_number" field.
func DefaultModelNumberEqualFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEqualFold(FieldDefaultModelNumber, v))
}

// DefaultModelNumberContainsFold applies the ContainsFold predicate on the "default_model_number" field.
func DefaultModelNumberContainsFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContainsFold(FieldDefaultModelNumber, v))
}

// DefaultLifetimeWarrantyEQ applies the EQ predicate on the "default_lifetime_warranty" field.
func DefaultLifetimeWarrantyEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultLifetimeWarranty, v))
}

// DefaultLifetimeWarrantyNEQ applies the NEQ predicate on the "default_lifetime_warranty" field.
func DefaultLifetimeWarrantyNEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDefaultLifetimeWarranty, v))
}

// DefaultWarrantyDetailsEQ applies the EQ predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsNEQ applies the NEQ predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsNEQ(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsIn applies the In predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIn(FieldDefaultWarrantyDetails, vs...))
}

// DefaultWarrantyDetailsNotIn applies the NotIn predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsNotIn(vs ...string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotIn(FieldDefaultWarrantyDetails, vs...))
}

// DefaultWarrantyDetailsGT applies the GT predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsGT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGT(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsGTE applies the GTE predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsGTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldGTE(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsLT applies the LT predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsLT(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLT(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsLTE applies the LTE predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsLTE(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldLTE(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsContains applies the Contains predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsContains(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContains(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsHasPrefix applies the HasPrefix predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsHasPrefix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasPrefix(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsHasSuffix applies the HasSuffix predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsHasSuffix(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldHasSuffix(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsIsNil applies the IsNil predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsIsNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIsNull(FieldDefaultWarrantyDetails))
}

// DefaultWarrantyDetailsNotNil applies the NotNil predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsNotNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotNull(FieldDefaultWarrantyDetails))
}

// DefaultWarrantyDetailsEqualFold applies the EqualFold predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsEqualFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEqualFold(FieldDefaultWarrantyDetails, v))
}

// DefaultWarrantyDetailsContainsFold applies the ContainsFold predicate on the "default_warranty_details" field.
func DefaultWarrantyDetailsContainsFold(v string) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldContainsFold(FieldDefaultWarrantyDetails, v))
}

// IncludeWarrantyFieldsEQ applies the EQ predicate on the "include_warranty_fields" field.
func IncludeWarrantyFieldsEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldIncludeWarrantyFields, v))
}

// IncludeWarrantyFieldsNEQ applies the NEQ predicate on the "include_warranty_fields" field.
func IncludeWarrantyFieldsNEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldIncludeWarrantyFields, v))
}

// IncludePurchaseFieldsEQ applies the EQ predicate on the "include_purchase_fields" field.
func IncludePurchaseFieldsEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldIncludePurchaseFields, v))
}

// IncludePurchaseFieldsNEQ applies the NEQ predicate on the "include_purchase_fields" field.
func IncludePurchaseFieldsNEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldIncludePurchaseFields, v))
}

// IncludeSoldFieldsEQ applies the EQ predicate on the "include_sold_fields" field.
func IncludeSoldFieldsEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldEQ(FieldIncludeSoldFields, v))
}

// IncludeSoldFieldsNEQ applies the NEQ predicate on the "include_sold_fields" field.
func IncludeSoldFieldsNEQ(v bool) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNEQ(FieldIncludeSoldFields, v))
}

// DefaultTagIdsIsNil applies the IsNil predicate on the "default_tag_ids" field.
func DefaultTagIdsIsNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldIsNull(FieldDefaultTagIds))
}

// DefaultTagIdsNotNil applies the NotNil predicate on the "default_tag_ids" field.
func DefaultTagIdsNotNil() predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.FieldNotNull(FieldDefaultTagIds))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.ItemTemplate {
	return predicate.ItemTemplate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.ItemTemplate {
	return predicate.ItemTemplate(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFields applies the HasEdge predicate on the "fields" edge.
func HasFields() predicate.ItemTemplate {
	return predicate.ItemTemplate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FieldsTable, FieldsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFieldsWith applies the HasEdge predicate on the "fields" edge with a given conditions (other predicates).
func HasFieldsWith(preds ...predicate.TemplateField) predicate.ItemTemplate {
	return predicate.ItemTemplate(func(s *sql.Selector) {
		step := newFieldsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocation applies the HasEdge predicate on the "location" edge.
func HasLocation() predicate.ItemTemplate {
	return predicate.ItemTemplate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.Location) predicate.ItemTemplate {
	return predicate.ItemTemplate(func(s *sql.Selector) {
		step := newLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItemTemplate) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItemTemplate) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItemTemplate) predicate.ItemTemplate {
	return predicate.ItemTemplate(sql.NotPredicates(p))
}
