// Code generated by ent, DO NOT EDIT.

package maintenanceplan

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the maintenanceplan type in the database.
	Label = "maintenance_plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIntervalValue holds the string denoting the interval_value field in the database.
	FieldIntervalValue = "interval_value"
	// FieldIntervalUnit holds the string denoting the interval_unit field in the database.
	FieldIntervalUnit = "interval_unit"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldLastCompletedAt holds the string denoting the last_completed_at field in the database.
	FieldLastCompletedAt = "last_completed_at"
	// FieldNextDueAt holds the string denoting the next_due_at field in the database.
	FieldNextDueAt = "next_due_at"
	// EdgeEntity holds the string denoting the entity edge name in mutations.
	EdgeEntity = "entity"
	// EdgeMaintenanceEntries holds the string denoting the maintenance_entries edge name in mutations.
	EdgeMaintenanceEntries = "maintenance_entries"
	// Table holds the table name of the maintenanceplan in the database.
	Table = "maintenance_plans"
	// EntityTable is the table that holds the entity relation/edge.
	EntityTable = "maintenance_plans"
	// EntityInverseTable is the table name for the Entity entity.
	// It exists in this package in order to avoid circular dependency with the "entity" package.
	EntityInverseTable = "entities"
	// EntityColumn is the table column denoting the entity relation/edge.
	EntityColumn = "entity_id"
	// MaintenanceEntriesTable is the table that holds the maintenance_entries relation/edge.
	MaintenanceEntriesTable = "maintenance_entries"
	// MaintenanceEntriesInverseTable is the table name for the MaintenanceEntry entity.
	// It exists in this package in order to avoid circular dependency with the "maintenanceentry" package.
	MaintenanceEntriesInverseTable = "maintenance_entries"
	// MaintenanceEntriesColumn is the table column denoting the maintenance_entries relation/edge.
	MaintenanceEntriesColumn = "plan_id"
)

// Columns holds all SQL columns for maintenanceplan fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEntityID,
	FieldName,
	FieldDescription,
	FieldIntervalValue,
	FieldIntervalUnit,
	FieldActive,
	FieldLastCompletedAt,
	FieldNextDueAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// IntervalValueValidator is a validator for the "interval_value" field. It is called by the builders before save.
	IntervalValueValidator func(int) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// IntervalUnit defines the type for the "interval_unit" enum field.
type IntervalUnit string

// IntervalUnit values.
const (
	IntervalUnitHour  IntervalUnit = "hour"
	IntervalUnitDay   IntervalUnit = "day"
	IntervalUnitWeek  IntervalUnit = "week"
	IntervalUnitMonth IntervalUnit = "month"
	IntervalUnitYear  IntervalUnit = "year"
)

func (iu IntervalUnit) String() string {
	return string(iu)
}

// IntervalUnitValidator is a validator for the "interval_unit" field enum values. It is called by the builders before save.
func IntervalUnitValidator(iu IntervalUnit) error {
	switch iu {
	case IntervalUnitHour, IntervalUnitDay, IntervalUnitWeek, IntervalUnitMonth, IntervalUnitYear:
		return nil
	default:
		return fmt.Errorf("maintenanceplan: invalid enum value for interval_unit field: %q", iu)
	}
}

// OrderOption defines the ordering options for the MaintenancePlan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIntervalValue orders the results by the interval_value field.
func ByIntervalValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalValue, opts...).ToFunc()
}

// ByIntervalUnit orders the results by the interval_unit field.
func ByIntervalUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalUnit, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByLastCompletedAt orders the results by the last_completed_at field.
func ByLastCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCompletedAt, opts...).ToFunc()
}

// ByNextDueAt orders the results by the next_due_at field.
func ByNextDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextDueAt, opts...).ToFunc()
}

// ByEntityField orders the results by entity field.
func ByEntityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntityStep(), sql.OrderByField(field, opts...))
	}
}

// ByMaintenanceEntriesCount orders the results by maintenance_entries count.
func ByMaintenanceEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMaintenanceEntriesStep(), opts...)
	}
}

// ByMaintenanceEntries orders the results by maintenance_entries terms.
func ByMaintenanceEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMaintenanceEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEntityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntityTable, EntityColumn),
	)
}
func newMaintenanceEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MaintenanceEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MaintenanceEntriesTable, MaintenanceEntriesColumn),
	)
}
