name: Pull Request CI

on:
  pull_request:
    branches:
      - main
      - vnext

    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/partial-backend.yaml'
      - '.github/workflows/partial-frontend.yaml'
      - '.github/workflows/e2e-partial.yaml'
      - '.github/workflows/pull-requests.yaml'

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/partial-backend.yaml

  frontend-tests:
    name: "Frontend Tests"
    uses: ./.github/workflows/partial-frontend.yaml

  e2e-tests:
    name: "End-to-End Playwright Tests"
    uses: ./.github/workflows/e2e-partial.yaml